### ISSUE TITLE
Using Custom Histories - Typescript throws type error

### ISSUE THREAD

**Issue by GeekOnGadgets** [andrew-w-ross/typings-history#2]
Problem
Was using Custom Histories in order to make URL Pretty and typescript is throwing a type check error from the History module.

const appHistory = useRouterHistory(createHashHistory)({ queryKey: false });
Error 
Argument of type '{ queryKey: boolean; }' is not assignable to parameter of type 'HistoryOptions'.
Object literal may only specify known properties, and 'queryKey' does not exist in type 'HistoryOptions'.

Question
After looking at the type file interface HistoryOptions is expecting a function - not sure why ?
interface HistoryOptions { getUserConfirmation?(message: string, callback: (boolean) => void): void; }
is this type file wrong ?

Solution
Not sure this is the right way to address the problem, 
const appHistory = useRouterHistory(createHashHistory)(() => { return { queryKey: false } });

Thanks to @edwin-nz for helping with this problem.

Can someone else please put more light on this issue?

Thanks

**Comment by andrew-w-ross** [comment]
@GeekOnGadgets Hey sorry for the long response. I'll have a chance to actually look at this on the weekend so I'll get back to you on this issue then. 

As for the `HistoryOptions { getUserConfirmation?(message: string, callback: (boolean) => void): void; }` typing. I have a general rule about making sure the documentation example code for a library would work with the type definitions. 

If you have a look at [history documentation for confirm navigation](https://github.com/mjackson/history/blob/master/docs/ConfirmingNavigation.md) that typing is needed to let the below snippet pass.

``` javascript
const history = createHistory({
  getUserConfirmation(message, callback) {
    callback(window.confirm(message)) // The default behavior
  }
})
```
