### ISSUE TITLE
Activate Travis CI

### ISSUE THREAD

**Issue by vslinko** [andrew-w-ross/typings-history#5]
@andrew-w-ross could you activate Travis CI?
https://travis-ci.org/andrew-w-ross/typings-history

**Comment by andrew-w-ross** [comment]
@vslinko I want to but travis is trying to get access to my work organization info and I'm not entirely sure what that allows. It also doesn't seem like I can deny it access, I'll e-mail someone at travis and my work and see exactly whats up.

**Comment by andrew-w-ross** [comment]
@vslinko Ok activated
